const github = {
  profile: {
    id: '5244986',
    nodeId: 'MDQ6VXNlcjUyNDQ5ODY=',
    displayName: 'Marco Biedermann',
    username: 'marcobiedermann',
    profileUrl: 'https://github.com/marcobiedermann',
    photos: [{ value: 'https://avatars.githubusercontent.com/u/5244986?v=4' }],
    provider: 'github',
    _raw: {
      login: 'marcobiedermann',
      id: 5244986,
      node_id: 'MDQ6VXNlcjUyNDQ5ODY=',
      avatar_url: 'https://avatars.githubusercontent.com/u/5244986?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/marcobiedermann',
      html_url: 'https://github.com/marcobiedermann',
      followers_url: 'https://api.github.com/users/marcobiedermann/followers',
      following_url: 'https://api.github.com/users/marcobiedermann/following{/other_user}',
      gists_url: 'https://api.github.com/users/marcobiedermann/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/marcobiedermann/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/marcobiedermann/subscriptions',
      organizations_url: 'https://api.github.com/users/marcobiedermann/orgs',
      repos_url: 'https://api.github.com/users/marcobiedermann/repos',
      events_url: 'https://api.github.com/users/marcobiedermann/events{/privacy}',
      received_events_url: 'https://api.github.com/users/marcobiedermann/received_events',
      type: 'User',
      site_admin: false,
      name: 'Marco Biedermann',
      company: '@mobimeo',
      blog: 'https://marcobiedermann.com',
      location: 'Berlin, Germany',
      email: null,
      hireable: true,
      bio: 'Senior Full-Stack JavaScript Engineer passionate about TypeScript, Node.js, React, and Open Source \\\\r\\\\nworking @mobimeo based in Berlin.',
      twitter_username: 'BiedermannMarco',
      public_repos: 52,
      public_gists: 27,
      followers: 177,
      following: 70,
      created_at: '2013-08-16T13:42:53Z',
      updated_at: '2022-03-01T15:13:15Z',
    },
    _json: {
      login: 'marcobiedermann',
      id: 5244986,
      node_id: 'MDQ6VXNlcjUyNDQ5ODY=',
      avatar_url: 'https://avatars.githubusercontent.com/u/5244986?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/marcobiedermann',
      html_url: 'https://github.com/marcobiedermann',
      followers_url: 'https://api.github.com/users/marcobiedermann/followers',
      following_url: 'https://api.github.com/users/marcobiedermann/following{/other_user}',
      gists_url: 'https://api.github.com/users/marcobiedermann/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/marcobiedermann/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/marcobiedermann/subscriptions',
      organizations_url: 'https://api.github.com/users/marcobiedermann/orgs',
      repos_url: 'https://api.github.com/users/marcobiedermann/repos',
      events_url: 'https://api.github.com/users/marcobiedermann/events{/privacy}',
      received_events_url: 'https://api.github.com/users/marcobiedermann/received_events',
      type: 'User',
      site_admin: false,
      name: 'Marco Biedermann',
      company: '@mobimeo',
      blog: 'https://marcobiedermann.com',
      location: 'Berlin, Germany',
      email: null,
      hireable: true,
      bio: 'Senior Full-Stack JavaScript Engineer passionate about TypeScript, Node.js, React, and Open Source \\r\\nworking @mobimeo based in Berlin.',
      twitter_username: 'BiedermannMarco',
      public_repos: 52,
      public_gists: 27,
      followers: 177,
      following: 70,
      created_at: '2013-08-16T13:42:53Z',
      updated_at: '2022-03-01T15:13:15Z',
    },
    emails: [{ value: 'marco.biedermann@gmx.de' }],
  },
};

export default github;
