name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
  GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⏬ Checkout
        uses: actions/checkout@v2

      - name: 🔢 Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: ⚙️ Use Node.js (.nvmrc)
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: 🔋 Install
        run: npm ci

      - name: 🤖 Linting
        run: npm run lint

      - name: 🧪 Testing
        run: npm run test:ci

      - name: 🛠️ Building
        run: npm run build

      - name: 📊 Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
